all:
	gfortran my_kind.f90 constants.f90 file.f90 string.f90 global_parameters.f90 object.f90 planetary_system.f90 parser.f90 physics.f90 planetary_motion.f90 -o planetary_motion
	# Please copy `input.dat` from `run` directory!
	# Then, to run Planetary motion simulator:
	# ./planetary_motion
