#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cmake -DDIRECTX=FALSE -DCMAKE_TOOLCHAIN_FILE=${script_dir}/w64.cmake ${script_dir} && nice -19 make -j $(($(nproc) - 1))
cp -v ./external/zlib-1.2.11/libzlib.dll zlib1.dll
