#!/bin/bash

# Modified from original found in:
# http://swarminglogic.com/article/2014_11_crosscompile2#toc19

current_dir=$(pwd)
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$script_dir"

mkdir glew_build
cd glew_build

if [ ! -f glew-1.11.0.tgz ]
then
    # Download glew 1.11.0
    wget http://downloads.sourceforge.net/project/glew/glew/1.11.0/glew-1.11.0.tgz
fi

if [ ! -d glew-1.11.0 ]
then
    # Extract files and directories.
    tar xf glew-1.11.0.tgz
fi
cd glew-1.11.0/

PREFIX="$script_dir"/cross-tools/
TOOLSET=x86_64-w64-mingw32
CROSSPATH=$PREFIX/$TOOLSET

# Slightly trickier, since it doesn't use configure
make SYSTEM=linux-mingw64 \
    CC=${TOOLSET}-gcc \
    LD=${TOOLSET}-ld \
    LDFLAGS.EXTRA=-L${CROSSPATH}/lib \
    GLEW_PREFIX=${CROSSPATH} \
    GLEW_DEST=${CROSSPATH}

make SYSTEM=linux-mingw64 \
    CC=${TOOLSET}-gcc \
    LD=${TOOLSET}-ld \
    LDFLAGS.EXTRA=-L${CROSSPATH}/lib \
    GLEW_PREFIX=${CROSSPATH} \
    GLEW_DEST=${CROSSPATH} install

cd "$current_dir"
