#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CC=$(which clang) CXX=$(which clang++) cmake ${script_dir} -DCMAKE_C_FLAGS="-gdwarf-4" -DCMAKE_CXX_FLAGS="-gdwarf-4" -DCMAKE_BUILD_TYPE=Debug -DDO_UNIT_TESTS_WITH_GOOGLE_TEST=true && nice -19 make -j $(($(nproc) - 1))
