#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CC=$(which gcc) CXX=$(which g++) cmake -G Ninja ${script_dir} -DCMAKE_BUILD_TYPE=Debug -DDO_UNIT_TESTS_WITH_GOOGLE_TEST=true && nice -19 ninja -j $(($(nproc) - 1))
