#!/usr/bin/python3

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

print("Hello from Visualize planetary motion!")

trayectory1_x = np.loadtxt("processed_output.txt", usecols = (2))
trayectory1_y = np.loadtxt("processed_output.txt", usecols = (3))
trayectory1_z = np.loadtxt("processed_output.txt", usecols = (4))
n_rows = len(trayectory1_x)
print("Number of rows in data: " + str(n_rows))

trayectory2_x = np.loadtxt("processed_output.txt", usecols = (6))
trayectory2_y = np.loadtxt("processed_output.txt", usecols = (7))
trayectory2_z = np.loadtxt("processed_output.txt", usecols = (8))

# Open figure
fig = plt.figure(figsize=(20,15), constrained_layout = True)
ax = fig.add_subplot(n_rows, projection = '3d')
ax.scatter(trayectory1_x, trayectory1_y, trayectory1_z, color = 'red')
ax.scatter(trayectory2_x, trayectory2_y, trayectory2_z, color = 'blue')

plt.savefig('trayectories1.pdf', bbox_inches = 'tight', dpi = 300)
plt.show()
